#!/bin/sh

set -e

TEST_REPORT=test_report.txt

fail() {
    echo "FAIL"
    cat $TEST_REPORT
    rm $TEST_REPORT
    exit 1
}

mydiff() {
    echo "kompare $1 $2"
    diff $1 $2
}

test() {
    echo -n "Testing $1 ... "
    (./make $1 > $TEST_REPORT 2>&1) || fail
    (mydiff examples/$1.c build-output/$1/main.c > $TEST_REPORT 2>&1) || fail
    echo "OK"
    rm $TEST_REPORT
}

test Blink
test DoubleBlink
test UART
test Input
test Combine
test Filter
