// This file is automatically generated.

#include <avr/io.h>
#include <stdbool.h>

struct list {
    uint8_t size;
    void* values;
};

static void input_timer();

static void stream_1(uint8_t arg, void* value);

static void stream_2(uint8_t arg, void* value);

static void stream_3(uint8_t arg, void* value);

static void stream_4(uint8_t arg, void* value);

static void stream_5(uint8_t arg, void* value);

static void input_timer() {
  uint16_t temp0;
  temp0 = TCNT1;
  TCNT1 = 0;
  stream_1(0, (void*)(&temp0));
}

static void stream_1(uint8_t arg, void* value) {
  static uint16_t input_1 = 0;
  bool temp1;
  uint16_t temp2;
  uint16_t temp3;
  uint16_t temp4;
  uint16_t temp5;
  static uint16_t input_0;
  switch (arg) {
    case 0:
      input_0 = *((uint16_t*)value);
      break;
  }
  temp1 = input_1 > 10000;
  temp2 = input_1 - 10000;
  temp3 = temp2 + input_0;
  temp4 = input_1 + input_0;
  if (temp1) {
    temp5 = temp3;
  } else {
    temp5 = temp4;
  }
  input_1 = temp5;
  stream_2(0, (void*)(&input_1));
}

static void stream_2(uint8_t arg, void* value) {
  bool temp6;
  bool temp7;
  static uint16_t input_0;
  switch (arg) {
    case 0:
      input_0 = *((uint16_t*)value);
      break;
  }
  temp6 = input_0 > 10000;
  temp7 = false;
  if (temp6) {
    temp7 = true;
  }
  if (temp7) {
    stream_3(0, (void*)(&input_0));
  }
}

static void stream_3(uint8_t arg, void* value) {
  static uint16_t input_1 = 0;
  uint16_t temp8;
  static uint16_t input_0;
  switch (arg) {
    case 0:
      input_0 = *((uint16_t*)value);
      break;
  }
  temp8 = input_1 + 1;
  input_1 = temp8;
  stream_4(0, (void*)(&input_1));
}

static void stream_4(uint8_t arg, void* value) {
  bool temp9;
  static uint16_t input_0;
  switch (arg) {
    case 0:
      input_0 = *((uint16_t*)value);
      break;
  }
  temp9 = (input_0) % 2 == 0;
  stream_5(0, (void*)(&temp9));
}

static void stream_5(uint8_t arg, void* value) {
  static bool input_0;
  switch (arg) {
    case 0:
      input_0 = *((bool*)value);
      break;
  }
  if (input_0) {
    PORTB |= (1 << PB5);
  } else {
    PORTB &= ~(1 << PB5);
  }
}

int main(void) {
  TCCR1B |= (1 << CS12);
  TCCR1B |= (1 << CS10);
  DDRB |= (1 << PB5);
  while (1) {
    input_timer();
  }
  return 0;
}
