// This file is automatically generated.

#include <avr/io.h>
#include <util/delay_basic.h>
#include <stdbool.h>

struct list {
    uint8_t size;
    void* values;
};

struct tuple2 {
    void* value0;
    void* value1;
};

struct tuple6 {
    void* value0;
    void* value1;
    void* value2;
    void* value3;
    void* value4;
    void* value5;
};

static void input_a0();

static void input_timer();

static void stream_1(uint8_t arg, void* value);

static void stream_2(uint8_t arg, void* value);

static void stream_3(uint8_t arg, void* value);

static void stream_4(uint8_t arg, void* value);

static void stream_5(uint8_t arg, void* value);

static void stream_6(uint8_t arg, void* value);

static void stream_7(uint8_t arg, void* value);

static void stream_9(uint8_t arg, void* value);

static void stream_10(uint8_t arg, void* value);

static void stream_8(uint8_t arg, void* value);

static void input_a0() {
  uint8_t temp0;
  uint8_t temp1;
  uint16_t temp2;
  ADMUX &= ~(1 << MUX3);
  ADMUX &= ~(1 << MUX2);
  ADMUX &= ~(1 << MUX1);
  ADMUX &= ~(1 << MUX0);
  ADCSRA |= (1 << ADSC);
  while ((ADCSRA & (1 << ADSC)) != 0) {
  }
  temp0 = ADCL;
  temp1 = ADCH;
  temp2 = temp0 | (temp1 << 8);
  stream_1(0, (void*)(&temp2));
}

static void input_timer() {
  uint16_t temp3;
  temp3 = TCNT1;
  TCNT1 = 0;
  stream_2(1, (void*)(&temp3));
}

static void stream_1(uint8_t arg, void* value) {
  uint16_t input_0 = *((uint16_t*)value);
  uint16_t temp4;
  temp4 = (1000 + (input_0 * 20));
  stream_2(0, (void*)(&temp4));
}

static void stream_2(uint8_t arg, void* value) {
  static uint16_t input_0;
  static uint16_t input_1;
  uint16_t temp5;
  uint16_t temp6;
  struct tuple2 temp7;
  switch (arg) {
    case 0:
      input_0 = *((uint16_t*)value);
      break;
    case 1:
      input_1 = *((uint16_t*)value);
      break;
  }
  temp5 = input_0;
  temp6 = input_1;
  temp7.value0 = (void*)&temp5;
  temp7.value1 = (void*)&temp6;
  stream_3(0, (void*)(&temp7));
}

static void stream_3(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  static uint16_t temp8 = 0;
  static uint16_t temp9 = 0;
  static struct tuple2 input_1 = { .value0 = (void*)&temp8, .value1 = (void*)&temp9 };
  uint16_t temp10;
  uint16_t temp11;
  struct tuple2 temp12;
  uint16_t temp13;
  uint16_t temp14;
  struct tuple2 temp15;
  struct tuple2 temp16;
  temp10 = 0;
  temp11 = 0;
  temp12.value0 = (void*)&temp10;
  temp12.value1 = (void*)&temp11;
  temp13 = 1;
  temp14 = (*((uint16_t*)input_1.value1) + *((uint16_t*)input_0.value1));
  temp15.value0 = (void*)&temp13;
  temp15.value1 = (void*)&temp14;
  if (((*((uint16_t*)input_1.value1) + *((uint16_t*)input_0.value1)) > *((uint16_t*)input_0.value0))) {
    temp16 = temp12;
  } else {
    temp16 = temp15;
  }
  *((uint16_t*)input_1.value0) = *((uint16_t*)temp16.value0);
  *((uint16_t*)input_1.value1) = *((uint16_t*)temp16.value1);
  stream_4(0, (void*)(&input_1));
}

static void stream_4(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  if (*((uint16_t*)input_0.value0) == 0) {
    stream_5(0, (void*)(&input_0));
  }
}

static void stream_5(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  bool temp17;
  temp17 = 0;
  stream_6(0, (void*)(&temp17));
}

static void stream_6(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  static bool temp18 = false;
  static bool temp19 = true;
  static struct tuple2 input_1 = { .value0 = (void*)&temp18, .value1 = (void*)&temp19 };
  bool temp20;
  bool temp21;
  struct tuple2 temp22;
  temp20 = *((bool*)input_1.value1);
  temp21 = *((bool*)input_1.value0);
  temp22.value0 = (void*)&temp20;
  temp22.value1 = (void*)&temp21;
  *((bool*)input_1.value0) = *((bool*)temp22.value0);
  *((bool*)input_1.value1) = *((bool*)temp22.value1);
  stream_7(0, (void*)(&input_1));
  stream_9(0, (void*)(&input_1));
}

static void stream_7(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  stream_8(0, (void*)(&*((bool*)input_0.value0)));
}

static void stream_9(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  stream_10(0, (void*)(&*((bool*)input_0.value1)));
}

static void stream_10(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  if (input_0) {
    PORTB |= (1 << PB4);
  } else {
    PORTB &= ~(1 << PB4);
  }
}

static void stream_8(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  if (input_0) {
    PORTB |= (1 << PB3);
  } else {
    PORTB &= ~(1 << PB3);
  }
}

int main(void) {
  ADCSRA |= (1 << ADEN);
  ADMUX |= (1 << REFS0);
  ADCSRA |= (1 << ADPS2);
  ADCSRA |= (1 << ADPS1);
  ADCSRA |= (1 << ADPS0);
  TCCR1B |= (1 << CS12);
  TCCR1B |= (1 << CS10);
  DDRB |= (1 << PB4);
  DDRB |= (1 << PB3);
  while (1) {
    input_a0();
    input_timer();
  }
  return 0;
}
