// This file is automatically generated.

#include <avr/io.h>
#include <stdbool.h>

static void stream_1(bool input_0);

static void stream_2();

static void stream_1(bool input_0) {
  bool output;
  if (input_0) {
    PORTB |= 0x20U;
  } else {
    PORTB &= ~(0x20U);
  }
}

static void stream_2() {
  bool output;
  output = (PINB & 0x10U) == 0x10U;
  stream_1(output);
}

int main(void) {
  DDRB |= 0x20U;
  DDRB &= ~(0x10U);
  PORTB |= 0x10U;
  while (1) {
    stream_2();
  }
  return 0;
}
