// This file is automatically generated.

#include <avr/io.h>
#include <util/delay_basic.h>
#include <stdbool.h>

struct list {
    uint8_t size;
    void* values;
};

struct tuple2 {
    void* value0;
    void* value1;
};

struct tuple6 {
    void* value0;
    void* value1;
    void* value2;
    void* value3;
    void* value4;
    void* value5;
};

static void input_timer();

static void stream_1(uint8_t arg, void* value);

static void stream_2(uint8_t arg, void* value);

static void stream_3(uint8_t arg, void* value);

static void stream_4(uint8_t arg, void* value);

static void stream_6(uint8_t arg, void* value);

static void stream_11(uint8_t arg, void* value);

static void stream_13(uint8_t arg, void* value);

static void stream_15(uint8_t arg, void* value);

static void stream_17(uint8_t arg, void* value);

static void stream_5(uint8_t arg, void* value);

static void stream_7(uint8_t arg, void* value);

static void stream_9(uint8_t arg, void* value);

static void stream_10(uint8_t arg, void* value);

static void stream_12(uint8_t arg, void* value);

static void stream_14(uint8_t arg, void* value);

static void stream_16(uint8_t arg, void* value);

static void stream_18(uint8_t arg, void* value);

static void stream_8(uint8_t arg, void* value);

static void stream_19(uint8_t arg, void* value);

static void stream_20(uint8_t arg, void* value);

static void input_timer() {
  uint16_t temp0;
  temp0 = TCNT1;
  TCNT1 = 0;
  stream_1(0, (void*)(&temp0));
}

static void stream_1(uint8_t arg, void* value) {
  static uint16_t input_1 = 0;
  uint16_t temp1;
  static uint16_t input_0;
  switch (arg) {
    case 0:
      input_0 = *((uint16_t*)value);
      break;
  }
  if ((input_1 > 10000)) {
    temp1 = ((input_1 - 10000) + input_0);
  } else {
    temp1 = (input_1 + input_0);
  }
  input_1 = temp1;
  stream_2(0, (void*)(&input_1));
}

static void stream_2(uint8_t arg, void* value) {
  static uint16_t input_0;
  switch (arg) {
    case 0:
      input_0 = *((uint16_t*)value);
      break;
  }
  if ((input_0 > 10000)) {
    stream_3(0, (void*)(&input_0));
  }
}

static void stream_3(uint8_t arg, void* value) {
  static uint16_t input_1 = 0;
  static uint16_t input_0;
  switch (arg) {
    case 0:
      input_0 = *((uint16_t*)value);
      break;
  }
  input_1 = (input_1 + 1);
  stream_4(0, (void*)(&input_1));
  stream_6(0, (void*)(&input_1));
}

static void stream_4(uint8_t arg, void* value) {
  bool temp2;
  static uint16_t input_0;
  switch (arg) {
    case 0:
      input_0 = *((uint16_t*)value);
      break;
  }
  temp2 = (input_0) % 2 == 0;
  stream_5(0, (void*)(&temp2));
}

static void stream_6(uint8_t arg, void* value) {
  bool temp3;
  bool temp4;
  bool temp5;
  bool temp6;
  bool temp7;
  uint16_t temp8;
  struct tuple6 temp9;
  bool temp10;
  bool temp11;
  bool temp12;
  bool temp13;
  bool temp14;
  uint16_t temp15;
  struct tuple6 temp16;
  bool temp17;
  bool temp18;
  bool temp19;
  bool temp20;
  bool temp21;
  uint16_t temp22;
  struct tuple6 temp23;
  bool temp24;
  bool temp25;
  bool temp26;
  bool temp27;
  bool temp28;
  uint16_t temp29;
  struct tuple6 temp30;
  bool temp31;
  bool temp32;
  bool temp33;
  bool temp34;
  bool temp35;
  uint16_t temp36;
  struct tuple6 temp37;
  bool temp38;
  bool temp39;
  bool temp40;
  bool temp41;
  bool temp42;
  uint16_t temp43;
  struct tuple6 temp44;
  bool temp45;
  bool temp46;
  bool temp47;
  bool temp48;
  bool temp49;
  uint16_t temp50;
  struct tuple6 temp51;
  bool temp52;
  bool temp53;
  bool temp54;
  bool temp55;
  bool temp56;
  uint16_t temp57;
  struct tuple6 temp58;
  bool temp59;
  bool temp60;
  bool temp61;
  bool temp62;
  bool temp63;
  uint16_t temp64;
  struct tuple6 temp65;
  bool temp66;
  bool temp67;
  bool temp68;
  bool temp69;
  bool temp70;
  uint16_t temp71;
  struct tuple6 temp72;
  bool temp73;
  bool temp74;
  bool temp75;
  bool temp76;
  bool temp77;
  uint16_t temp78;
  struct tuple6 temp79;
  bool temp80;
  bool temp81;
  bool temp82;
  bool temp83;
  bool temp84;
  uint16_t temp85;
  struct tuple6 temp86;
  bool temp87;
  bool temp88;
  bool temp89;
  bool temp90;
  bool temp91;
  uint16_t temp92;
  struct tuple6 temp93;
  bool temp94;
  bool temp95;
  bool temp96;
  bool temp97;
  bool temp98;
  uint16_t temp99;
  struct tuple6 temp100;
  bool temp101;
  bool temp102;
  bool temp103;
  bool temp104;
  bool temp105;
  uint16_t temp106;
  struct tuple6 temp107;
  bool temp108;
  bool temp109;
  bool temp110;
  bool temp111;
  bool temp112;
  uint16_t temp113;
  struct tuple6 temp114;
  bool temp115;
  bool temp116;
  bool temp117;
  bool temp118;
  bool temp119;
  uint16_t temp120;
  struct tuple6 temp121;
  bool temp122;
  bool temp123;
  bool temp124;
  bool temp125;
  bool temp126;
  uint16_t temp127;
  struct tuple6 temp128;
  bool temp129;
  bool temp130;
  bool temp131;
  bool temp132;
  bool temp133;
  uint16_t temp134;
  struct tuple6 temp135;
  bool temp136;
  bool temp137;
  bool temp138;
  bool temp139;
  bool temp140;
  uint16_t temp141;
  struct tuple6 temp142;
  bool temp143;
  bool temp144;
  bool temp145;
  bool temp146;
  bool temp147;
  uint16_t temp148;
  struct tuple6 temp149;
  bool temp150;
  bool temp151;
  bool temp152;
  bool temp153;
  bool temp154;
  uint16_t temp155;
  struct tuple6 temp156;
  bool temp157;
  bool temp158;
  bool temp159;
  bool temp160;
  bool temp161;
  uint16_t temp162;
  struct tuple6 temp163;
  bool temp164;
  bool temp165;
  bool temp166;
  bool temp167;
  bool temp168;
  uint16_t temp169;
  struct tuple6 temp170;
  bool temp171;
  bool temp172;
  bool temp173;
  bool temp174;
  bool temp175;
  uint16_t temp176;
  struct tuple6 temp177;
  bool temp178;
  bool temp179;
  bool temp180;
  bool temp181;
  bool temp182;
  uint16_t temp183;
  struct tuple6 temp184;
  bool temp185;
  bool temp186;
  bool temp187;
  bool temp188;
  bool temp189;
  uint16_t temp190;
  struct tuple6 temp191;
  bool temp192;
  bool temp193;
  bool temp194;
  bool temp195;
  bool temp196;
  uint16_t temp197;
  struct tuple6 temp198;
  bool temp199;
  bool temp200;
  bool temp201;
  bool temp202;
  bool temp203;
  uint16_t temp204;
  struct tuple6 temp205;
  bool temp206;
  bool temp207;
  bool temp208;
  bool temp209;
  bool temp210;
  uint16_t temp211;
  struct tuple6 temp212;
  bool temp213;
  bool temp214;
  bool temp215;
  bool temp216;
  bool temp217;
  uint16_t temp218;
  struct tuple6 temp219;
  bool temp220;
  bool temp221;
  bool temp222;
  bool temp223;
  bool temp224;
  uint16_t temp225;
  struct tuple6 temp226;
  bool temp227;
  bool temp228;
  bool temp229;
  bool temp230;
  bool temp231;
  uint16_t temp232;
  struct tuple6 temp233;
  bool temp234;
  bool temp235;
  bool temp236;
  bool temp237;
  bool temp238;
  uint16_t temp239;
  struct tuple6 temp240;
  bool temp241;
  bool temp242;
  bool temp243;
  bool temp244;
  bool temp245;
  uint16_t temp246;
  struct tuple6 temp247;
  bool temp248;
  bool temp249;
  bool temp250;
  bool temp251;
  bool temp252;
  uint16_t temp253;
  struct tuple6 temp254;
  bool temp255;
  bool temp256;
  bool temp257;
  bool temp258;
  bool temp259;
  uint16_t temp260;
  struct tuple6 temp261;
  bool temp262;
  bool temp263;
  bool temp264;
  bool temp265;
  bool temp266;
  uint16_t temp267;
  struct tuple6 temp268;
  bool temp269;
  bool temp270;
  bool temp271;
  bool temp272;
  bool temp273;
  uint16_t temp274;
  struct tuple6 temp275;
  bool temp276;
  bool temp277;
  bool temp278;
  bool temp279;
  bool temp280;
  uint16_t temp281;
  struct tuple6 temp282;
  bool temp283;
  bool temp284;
  bool temp285;
  bool temp286;
  bool temp287;
  uint16_t temp288;
  struct tuple6 temp289;
  bool temp290;
  bool temp291;
  bool temp292;
  bool temp293;
  bool temp294;
  uint16_t temp295;
  struct tuple6 temp296;
  static uint16_t input_0;
  switch (arg) {
    case 0:
      input_0 = *((uint16_t*)value);
      break;
  }
  temp3 = false;
  temp4 = false;
  temp5 = false;
  temp6 = true;
  temp7 = true;
  temp8 = 5600;
  temp9.value0 = (void*)&temp3;
  temp9.value1 = (void*)&temp4;
  temp9.value2 = (void*)&temp5;
  temp9.value3 = (void*)&temp6;
  temp9.value4 = (void*)&temp7;
  temp9.value5 = (void*)&temp8;
  temp10 = false;
  temp11 = false;
  temp12 = false;
  temp13 = true;
  temp14 = true;
  temp15 = 5600;
  temp16.value0 = (void*)&temp10;
  temp16.value1 = (void*)&temp11;
  temp16.value2 = (void*)&temp12;
  temp16.value3 = (void*)&temp13;
  temp16.value4 = (void*)&temp14;
  temp16.value5 = (void*)&temp15;
  temp17 = false;
  temp18 = false;
  temp19 = false;
  temp20 = true;
  temp21 = true;
  temp22 = 250;
  temp23.value0 = (void*)&temp17;
  temp23.value1 = (void*)&temp18;
  temp23.value2 = (void*)&temp19;
  temp23.value3 = (void*)&temp20;
  temp23.value4 = (void*)&temp21;
  temp23.value5 = (void*)&temp22;
  temp24 = false;
  temp25 = false;
  temp26 = false;
  temp27 = true;
  temp28 = false;
  temp29 = 100;
  temp30.value0 = (void*)&temp24;
  temp30.value1 = (void*)&temp25;
  temp30.value2 = (void*)&temp26;
  temp30.value3 = (void*)&temp27;
  temp30.value4 = (void*)&temp28;
  temp30.value5 = (void*)&temp29;
  temp31 = false;
  temp32 = false;
  temp33 = false;
  temp34 = true;
  temp35 = false;
  temp36 = 100;
  temp37.value0 = (void*)&temp31;
  temp37.value1 = (void*)&temp32;
  temp37.value2 = (void*)&temp33;
  temp37.value3 = (void*)&temp34;
  temp37.value4 = (void*)&temp35;
  temp37.value5 = (void*)&temp36;
  temp38 = false;
  temp39 = true;
  temp40 = false;
  temp41 = false;
  temp42 = false;
  temp43 = 100;
  temp44.value0 = (void*)&temp38;
  temp44.value1 = (void*)&temp39;
  temp44.value2 = (void*)&temp40;
  temp44.value3 = (void*)&temp41;
  temp44.value4 = (void*)&temp42;
  temp44.value5 = (void*)&temp43;
  temp45 = false;
  temp46 = false;
  temp47 = false;
  temp48 = false;
  temp49 = false;
  temp50 = 100;
  temp51.value0 = (void*)&temp45;
  temp51.value1 = (void*)&temp46;
  temp51.value2 = (void*)&temp47;
  temp51.value3 = (void*)&temp48;
  temp51.value4 = (void*)&temp49;
  temp51.value5 = (void*)&temp50;
  temp52 = false;
  temp53 = true;
  temp54 = false;
  temp55 = false;
  temp56 = false;
  temp57 = 100;
  temp58.value0 = (void*)&temp52;
  temp58.value1 = (void*)&temp53;
  temp58.value2 = (void*)&temp54;
  temp58.value3 = (void*)&temp55;
  temp58.value4 = (void*)&temp56;
  temp58.value5 = (void*)&temp57;
  temp59 = false;
  temp60 = false;
  temp61 = false;
  temp62 = false;
  temp63 = false;
  temp64 = 100;
  temp65.value0 = (void*)&temp59;
  temp65.value1 = (void*)&temp60;
  temp65.value2 = (void*)&temp61;
  temp65.value3 = (void*)&temp62;
  temp65.value4 = (void*)&temp63;
  temp65.value5 = (void*)&temp64;
  temp66 = false;
  temp67 = false;
  temp68 = false;
  temp69 = false;
  temp70 = true;
  temp71 = 2100;
  temp72.value0 = (void*)&temp66;
  temp72.value1 = (void*)&temp67;
  temp72.value2 = (void*)&temp68;
  temp72.value3 = (void*)&temp69;
  temp72.value4 = (void*)&temp70;
  temp72.value5 = (void*)&temp71;
  temp73 = false;
  temp74 = false;
  temp75 = false;
  temp76 = false;
  temp77 = false;
  temp78 = 100;
  temp79.value0 = (void*)&temp73;
  temp79.value1 = (void*)&temp74;
  temp79.value2 = (void*)&temp75;
  temp79.value3 = (void*)&temp76;
  temp79.value4 = (void*)&temp77;
  temp79.value5 = (void*)&temp78;
  temp80 = false;
  temp81 = false;
  temp82 = true;
  temp83 = true;
  temp84 = false;
  temp85 = 100;
  temp86.value0 = (void*)&temp80;
  temp86.value1 = (void*)&temp81;
  temp86.value2 = (void*)&temp82;
  temp86.value3 = (void*)&temp83;
  temp86.value4 = (void*)&temp84;
  temp86.value5 = (void*)&temp85;
  temp87 = false;
  temp88 = false;
  temp89 = false;
  temp90 = false;
  temp91 = false;
  temp92 = 100;
  temp93.value0 = (void*)&temp87;
  temp93.value1 = (void*)&temp88;
  temp93.value2 = (void*)&temp89;
  temp93.value3 = (void*)&temp90;
  temp93.value4 = (void*)&temp91;
  temp93.value5 = (void*)&temp92;
  temp94 = false;
  temp95 = true;
  temp96 = true;
  temp97 = true;
  temp98 = true;
  temp99 = 100;
  temp100.value0 = (void*)&temp94;
  temp100.value1 = (void*)&temp95;
  temp100.value2 = (void*)&temp96;
  temp100.value3 = (void*)&temp97;
  temp100.value4 = (void*)&temp98;
  temp100.value5 = (void*)&temp99;
  temp101 = true;
  temp102 = false;
  temp103 = true;
  temp104 = false;
  temp105 = false;
  temp106 = 100;
  temp107.value0 = (void*)&temp101;
  temp107.value1 = (void*)&temp102;
  temp107.value2 = (void*)&temp103;
  temp107.value3 = (void*)&temp104;
  temp107.value4 = (void*)&temp105;
  temp107.value5 = (void*)&temp106;
  temp108 = true;
  temp109 = false;
  temp110 = true;
  temp111 = true;
  temp112 = false;
  temp113 = 100;
  temp114.value0 = (void*)&temp108;
  temp114.value1 = (void*)&temp109;
  temp114.value2 = (void*)&temp110;
  temp114.value3 = (void*)&temp111;
  temp114.value4 = (void*)&temp112;
  temp114.value5 = (void*)&temp113;
  temp115 = true;
  temp116 = false;
  temp117 = true;
  temp118 = false;
  temp119 = true;
  temp120 = 100;
  temp121.value0 = (void*)&temp115;
  temp121.value1 = (void*)&temp116;
  temp121.value2 = (void*)&temp117;
  temp121.value3 = (void*)&temp118;
  temp121.value4 = (void*)&temp119;
  temp121.value5 = (void*)&temp120;
  temp122 = true;
  temp123 = false;
  temp124 = false;
  temp125 = true;
  temp126 = false;
  temp127 = 100;
  temp128.value0 = (void*)&temp122;
  temp128.value1 = (void*)&temp123;
  temp128.value2 = (void*)&temp124;
  temp128.value3 = (void*)&temp125;
  temp128.value4 = (void*)&temp126;
  temp128.value5 = (void*)&temp127;
  temp129 = true;
  temp130 = false;
  temp131 = true;
  temp132 = false;
  temp133 = true;
  temp134 = 100;
  temp135.value0 = (void*)&temp129;
  temp135.value1 = (void*)&temp130;
  temp135.value2 = (void*)&temp131;
  temp135.value3 = (void*)&temp132;
  temp135.value4 = (void*)&temp133;
  temp135.value5 = (void*)&temp134;
  temp136 = true;
  temp137 = false;
  temp138 = false;
  temp139 = false;
  temp140 = false;
  temp141 = 100;
  temp142.value0 = (void*)&temp136;
  temp142.value1 = (void*)&temp137;
  temp142.value2 = (void*)&temp138;
  temp142.value3 = (void*)&temp139;
  temp142.value4 = (void*)&temp140;
  temp142.value5 = (void*)&temp141;
  temp143 = true;
  temp144 = false;
  temp145 = false;
  temp146 = true;
  temp147 = false;
  temp148 = 100;
  temp149.value0 = (void*)&temp143;
  temp149.value1 = (void*)&temp144;
  temp149.value2 = (void*)&temp145;
  temp149.value3 = (void*)&temp146;
  temp149.value4 = (void*)&temp147;
  temp149.value5 = (void*)&temp148;
  temp150 = true;
  temp151 = false;
  temp152 = false;
  temp153 = false;
  temp154 = false;
  temp155 = 100;
  temp156.value0 = (void*)&temp150;
  temp156.value1 = (void*)&temp151;
  temp156.value2 = (void*)&temp152;
  temp156.value3 = (void*)&temp153;
  temp156.value4 = (void*)&temp154;
  temp156.value5 = (void*)&temp155;
  temp157 = true;
  temp158 = false;
  temp159 = true;
  temp160 = false;
  temp161 = false;
  temp162 = 100;
  temp163.value0 = (void*)&temp157;
  temp163.value1 = (void*)&temp158;
  temp163.value2 = (void*)&temp159;
  temp163.value3 = (void*)&temp160;
  temp163.value4 = (void*)&temp161;
  temp163.value5 = (void*)&temp162;
  temp164 = true;
  temp165 = false;
  temp166 = false;
  temp167 = false;
  temp168 = true;
  temp169 = 100;
  temp170.value0 = (void*)&temp164;
  temp170.value1 = (void*)&temp165;
  temp170.value2 = (void*)&temp166;
  temp170.value3 = (void*)&temp167;
  temp170.value4 = (void*)&temp168;
  temp170.value5 = (void*)&temp169;
  temp171 = true;
  temp172 = false;
  temp173 = true;
  temp174 = true;
  temp175 = true;
  temp176 = 100;
  temp177.value0 = (void*)&temp171;
  temp177.value1 = (void*)&temp172;
  temp177.value2 = (void*)&temp173;
  temp177.value3 = (void*)&temp174;
  temp177.value4 = (void*)&temp175;
  temp177.value5 = (void*)&temp176;
  temp178 = true;
  temp179 = false;
  temp180 = false;
  temp181 = true;
  temp182 = false;
  temp183 = 100;
  temp184.value0 = (void*)&temp178;
  temp184.value1 = (void*)&temp179;
  temp184.value2 = (void*)&temp180;
  temp184.value3 = (void*)&temp181;
  temp184.value4 = (void*)&temp182;
  temp184.value5 = (void*)&temp183;
  temp185 = true;
  temp186 = false;
  temp187 = true;
  temp188 = true;
  temp189 = false;
  temp190 = 100;
  temp191.value0 = (void*)&temp185;
  temp191.value1 = (void*)&temp186;
  temp191.value2 = (void*)&temp187;
  temp191.value3 = (void*)&temp188;
  temp191.value4 = (void*)&temp189;
  temp191.value5 = (void*)&temp190;
  temp192 = true;
  temp193 = false;
  temp194 = true;
  temp195 = false;
  temp196 = false;
  temp197 = 100;
  temp198.value0 = (void*)&temp192;
  temp198.value1 = (void*)&temp193;
  temp198.value2 = (void*)&temp194;
  temp198.value3 = (void*)&temp195;
  temp198.value4 = (void*)&temp196;
  temp198.value5 = (void*)&temp197;
  temp199 = true;
  temp200 = false;
  temp201 = true;
  temp202 = true;
  temp203 = true;
  temp204 = 100;
  temp205.value0 = (void*)&temp199;
  temp205.value1 = (void*)&temp200;
  temp205.value2 = (void*)&temp201;
  temp205.value3 = (void*)&temp202;
  temp205.value4 = (void*)&temp203;
  temp205.value5 = (void*)&temp204;
  temp206 = true;
  temp207 = false;
  temp208 = true;
  temp209 = false;
  temp210 = true;
  temp211 = 100;
  temp212.value0 = (void*)&temp206;
  temp212.value1 = (void*)&temp207;
  temp212.value2 = (void*)&temp208;
  temp212.value3 = (void*)&temp209;
  temp212.value4 = (void*)&temp210;
  temp212.value5 = (void*)&temp211;
  temp213 = true;
  temp214 = false;
  temp215 = true;
  temp216 = true;
  temp217 = false;
  temp218 = 100;
  temp219.value0 = (void*)&temp213;
  temp219.value1 = (void*)&temp214;
  temp219.value2 = (void*)&temp215;
  temp219.value3 = (void*)&temp216;
  temp219.value4 = (void*)&temp217;
  temp219.value5 = (void*)&temp218;
  temp220 = true;
  temp221 = true;
  temp222 = false;
  temp223 = false;
  temp224 = true;
  temp225 = 100;
  temp226.value0 = (void*)&temp220;
  temp226.value1 = (void*)&temp221;
  temp226.value2 = (void*)&temp222;
  temp226.value3 = (void*)&temp223;
  temp226.value4 = (void*)&temp224;
  temp226.value5 = (void*)&temp225;
  temp227 = true;
  temp228 = false;
  temp229 = true;
  temp230 = true;
  temp231 = false;
  temp232 = 100;
  temp233.value0 = (void*)&temp227;
  temp233.value1 = (void*)&temp228;
  temp233.value2 = (void*)&temp229;
  temp233.value3 = (void*)&temp230;
  temp233.value4 = (void*)&temp231;
  temp233.value5 = (void*)&temp232;
  temp234 = true;
  temp235 = true;
  temp236 = true;
  temp237 = true;
  temp238 = false;
  temp239 = 100;
  temp240.value0 = (void*)&temp234;
  temp240.value1 = (void*)&temp235;
  temp240.value2 = (void*)&temp236;
  temp240.value3 = (void*)&temp237;
  temp240.value4 = (void*)&temp238;
  temp240.value5 = (void*)&temp239;
  temp241 = true;
  temp242 = false;
  temp243 = true;
  temp244 = true;
  temp245 = false;
  temp246 = 100;
  temp247.value0 = (void*)&temp241;
  temp247.value1 = (void*)&temp242;
  temp247.value2 = (void*)&temp243;
  temp247.value3 = (void*)&temp244;
  temp247.value4 = (void*)&temp245;
  temp247.value5 = (void*)&temp246;
  temp248 = true;
  temp249 = true;
  temp250 = true;
  temp251 = true;
  temp252 = true;
  temp253 = 100;
  temp254.value0 = (void*)&temp248;
  temp254.value1 = (void*)&temp249;
  temp254.value2 = (void*)&temp250;
  temp254.value3 = (void*)&temp251;
  temp254.value4 = (void*)&temp252;
  temp254.value5 = (void*)&temp253;
  temp255 = true;
  temp256 = false;
  temp257 = false;
  temp258 = true;
  temp259 = false;
  temp260 = 100;
  temp261.value0 = (void*)&temp255;
  temp261.value1 = (void*)&temp256;
  temp261.value2 = (void*)&temp257;
  temp261.value3 = (void*)&temp258;
  temp261.value4 = (void*)&temp259;
  temp261.value5 = (void*)&temp260;
  temp262 = true;
  temp263 = false;
  temp264 = false;
  temp265 = false;
  temp266 = false;
  temp267 = 100;
  temp268.value0 = (void*)&temp262;
  temp268.value1 = (void*)&temp263;
  temp268.value2 = (void*)&temp264;
  temp268.value3 = (void*)&temp265;
  temp268.value4 = (void*)&temp266;
  temp268.value5 = (void*)&temp267;
  temp269 = true;
  temp270 = false;
  temp271 = false;
  temp272 = true;
  temp273 = true;
  temp274 = 100;
  temp275.value0 = (void*)&temp269;
  temp275.value1 = (void*)&temp270;
  temp275.value2 = (void*)&temp271;
  temp275.value3 = (void*)&temp272;
  temp275.value4 = (void*)&temp273;
  temp275.value5 = (void*)&temp274;
  temp276 = true;
  temp277 = true;
  temp278 = false;
  temp279 = true;
  temp280 = false;
  temp281 = 100;
  temp282.value0 = (void*)&temp276;
  temp282.value1 = (void*)&temp277;
  temp282.value2 = (void*)&temp278;
  temp282.value3 = (void*)&temp279;
  temp282.value4 = (void*)&temp280;
  temp282.value5 = (void*)&temp281;
  temp283 = true;
  temp284 = false;
  temp285 = false;
  temp286 = true;
  temp287 = false;
  temp288 = 100;
  temp289.value0 = (void*)&temp283;
  temp289.value1 = (void*)&temp284;
  temp289.value2 = (void*)&temp285;
  temp289.value3 = (void*)&temp286;
  temp289.value4 = (void*)&temp287;
  temp289.value5 = (void*)&temp288;
  temp290 = true;
  temp291 = true;
  temp292 = false;
  temp293 = false;
  temp294 = true;
  temp295 = 100;
  temp296.value0 = (void*)&temp290;
  temp296.value1 = (void*)&temp291;
  temp296.value2 = (void*)&temp292;
  temp296.value3 = (void*)&temp293;
  temp296.value4 = (void*)&temp294;
  temp296.value5 = (void*)&temp295;
  stream_7(0, (void*)(&temp9));
  stream_9(0, (void*)(&temp9));
  stream_11(0, (void*)(&temp9));
  stream_13(0, (void*)(&temp9));
  stream_15(0, (void*)(&temp9));
  stream_17(0, (void*)(&temp9));
  stream_7(0, (void*)(&temp16));
  stream_9(0, (void*)(&temp16));
  stream_11(0, (void*)(&temp16));
  stream_13(0, (void*)(&temp16));
  stream_15(0, (void*)(&temp16));
  stream_17(0, (void*)(&temp16));
  stream_7(0, (void*)(&temp23));
  stream_9(0, (void*)(&temp23));
  stream_11(0, (void*)(&temp23));
  stream_13(0, (void*)(&temp23));
  stream_15(0, (void*)(&temp23));
  stream_17(0, (void*)(&temp23));
  stream_7(0, (void*)(&temp30));
  stream_9(0, (void*)(&temp30));
  stream_11(0, (void*)(&temp30));
  stream_13(0, (void*)(&temp30));
  stream_15(0, (void*)(&temp30));
  stream_17(0, (void*)(&temp30));
  stream_7(0, (void*)(&temp37));
  stream_9(0, (void*)(&temp37));
  stream_11(0, (void*)(&temp37));
  stream_13(0, (void*)(&temp37));
  stream_15(0, (void*)(&temp37));
  stream_17(0, (void*)(&temp37));
  stream_7(0, (void*)(&temp44));
  stream_9(0, (void*)(&temp44));
  stream_11(0, (void*)(&temp44));
  stream_13(0, (void*)(&temp44));
  stream_15(0, (void*)(&temp44));
  stream_17(0, (void*)(&temp44));
  stream_7(0, (void*)(&temp51));
  stream_9(0, (void*)(&temp51));
  stream_11(0, (void*)(&temp51));
  stream_13(0, (void*)(&temp51));
  stream_15(0, (void*)(&temp51));
  stream_17(0, (void*)(&temp51));
  stream_7(0, (void*)(&temp58));
  stream_9(0, (void*)(&temp58));
  stream_11(0, (void*)(&temp58));
  stream_13(0, (void*)(&temp58));
  stream_15(0, (void*)(&temp58));
  stream_17(0, (void*)(&temp58));
  stream_7(0, (void*)(&temp65));
  stream_9(0, (void*)(&temp65));
  stream_11(0, (void*)(&temp65));
  stream_13(0, (void*)(&temp65));
  stream_15(0, (void*)(&temp65));
  stream_17(0, (void*)(&temp65));
  stream_7(0, (void*)(&temp72));
  stream_9(0, (void*)(&temp72));
  stream_11(0, (void*)(&temp72));
  stream_13(0, (void*)(&temp72));
  stream_15(0, (void*)(&temp72));
  stream_17(0, (void*)(&temp72));
  stream_7(0, (void*)(&temp79));
  stream_9(0, (void*)(&temp79));
  stream_11(0, (void*)(&temp79));
  stream_13(0, (void*)(&temp79));
  stream_15(0, (void*)(&temp79));
  stream_17(0, (void*)(&temp79));
  stream_7(0, (void*)(&temp86));
  stream_9(0, (void*)(&temp86));
  stream_11(0, (void*)(&temp86));
  stream_13(0, (void*)(&temp86));
  stream_15(0, (void*)(&temp86));
  stream_17(0, (void*)(&temp86));
  stream_7(0, (void*)(&temp93));
  stream_9(0, (void*)(&temp93));
  stream_11(0, (void*)(&temp93));
  stream_13(0, (void*)(&temp93));
  stream_15(0, (void*)(&temp93));
  stream_17(0, (void*)(&temp93));
  stream_7(0, (void*)(&temp100));
  stream_9(0, (void*)(&temp100));
  stream_11(0, (void*)(&temp100));
  stream_13(0, (void*)(&temp100));
  stream_15(0, (void*)(&temp100));
  stream_17(0, (void*)(&temp100));
  stream_7(0, (void*)(&temp107));
  stream_9(0, (void*)(&temp107));
  stream_11(0, (void*)(&temp107));
  stream_13(0, (void*)(&temp107));
  stream_15(0, (void*)(&temp107));
  stream_17(0, (void*)(&temp107));
  stream_7(0, (void*)(&temp114));
  stream_9(0, (void*)(&temp114));
  stream_11(0, (void*)(&temp114));
  stream_13(0, (void*)(&temp114));
  stream_15(0, (void*)(&temp114));
  stream_17(0, (void*)(&temp114));
  stream_7(0, (void*)(&temp121));
  stream_9(0, (void*)(&temp121));
  stream_11(0, (void*)(&temp121));
  stream_13(0, (void*)(&temp121));
  stream_15(0, (void*)(&temp121));
  stream_17(0, (void*)(&temp121));
  stream_7(0, (void*)(&temp128));
  stream_9(0, (void*)(&temp128));
  stream_11(0, (void*)(&temp128));
  stream_13(0, (void*)(&temp128));
  stream_15(0, (void*)(&temp128));
  stream_17(0, (void*)(&temp128));
  stream_7(0, (void*)(&temp135));
  stream_9(0, (void*)(&temp135));
  stream_11(0, (void*)(&temp135));
  stream_13(0, (void*)(&temp135));
  stream_15(0, (void*)(&temp135));
  stream_17(0, (void*)(&temp135));
  stream_7(0, (void*)(&temp142));
  stream_9(0, (void*)(&temp142));
  stream_11(0, (void*)(&temp142));
  stream_13(0, (void*)(&temp142));
  stream_15(0, (void*)(&temp142));
  stream_17(0, (void*)(&temp142));
  stream_7(0, (void*)(&temp149));
  stream_9(0, (void*)(&temp149));
  stream_11(0, (void*)(&temp149));
  stream_13(0, (void*)(&temp149));
  stream_15(0, (void*)(&temp149));
  stream_17(0, (void*)(&temp149));
  stream_7(0, (void*)(&temp156));
  stream_9(0, (void*)(&temp156));
  stream_11(0, (void*)(&temp156));
  stream_13(0, (void*)(&temp156));
  stream_15(0, (void*)(&temp156));
  stream_17(0, (void*)(&temp156));
  stream_7(0, (void*)(&temp163));
  stream_9(0, (void*)(&temp163));
  stream_11(0, (void*)(&temp163));
  stream_13(0, (void*)(&temp163));
  stream_15(0, (void*)(&temp163));
  stream_17(0, (void*)(&temp163));
  stream_7(0, (void*)(&temp170));
  stream_9(0, (void*)(&temp170));
  stream_11(0, (void*)(&temp170));
  stream_13(0, (void*)(&temp170));
  stream_15(0, (void*)(&temp170));
  stream_17(0, (void*)(&temp170));
  stream_7(0, (void*)(&temp177));
  stream_9(0, (void*)(&temp177));
  stream_11(0, (void*)(&temp177));
  stream_13(0, (void*)(&temp177));
  stream_15(0, (void*)(&temp177));
  stream_17(0, (void*)(&temp177));
  stream_7(0, (void*)(&temp184));
  stream_9(0, (void*)(&temp184));
  stream_11(0, (void*)(&temp184));
  stream_13(0, (void*)(&temp184));
  stream_15(0, (void*)(&temp184));
  stream_17(0, (void*)(&temp184));
  stream_7(0, (void*)(&temp191));
  stream_9(0, (void*)(&temp191));
  stream_11(0, (void*)(&temp191));
  stream_13(0, (void*)(&temp191));
  stream_15(0, (void*)(&temp191));
  stream_17(0, (void*)(&temp191));
  stream_7(0, (void*)(&temp198));
  stream_9(0, (void*)(&temp198));
  stream_11(0, (void*)(&temp198));
  stream_13(0, (void*)(&temp198));
  stream_15(0, (void*)(&temp198));
  stream_17(0, (void*)(&temp198));
  stream_7(0, (void*)(&temp205));
  stream_9(0, (void*)(&temp205));
  stream_11(0, (void*)(&temp205));
  stream_13(0, (void*)(&temp205));
  stream_15(0, (void*)(&temp205));
  stream_17(0, (void*)(&temp205));
  stream_7(0, (void*)(&temp212));
  stream_9(0, (void*)(&temp212));
  stream_11(0, (void*)(&temp212));
  stream_13(0, (void*)(&temp212));
  stream_15(0, (void*)(&temp212));
  stream_17(0, (void*)(&temp212));
  stream_7(0, (void*)(&temp219));
  stream_9(0, (void*)(&temp219));
  stream_11(0, (void*)(&temp219));
  stream_13(0, (void*)(&temp219));
  stream_15(0, (void*)(&temp219));
  stream_17(0, (void*)(&temp219));
  stream_7(0, (void*)(&temp226));
  stream_9(0, (void*)(&temp226));
  stream_11(0, (void*)(&temp226));
  stream_13(0, (void*)(&temp226));
  stream_15(0, (void*)(&temp226));
  stream_17(0, (void*)(&temp226));
  stream_7(0, (void*)(&temp233));
  stream_9(0, (void*)(&temp233));
  stream_11(0, (void*)(&temp233));
  stream_13(0, (void*)(&temp233));
  stream_15(0, (void*)(&temp233));
  stream_17(0, (void*)(&temp233));
  stream_7(0, (void*)(&temp240));
  stream_9(0, (void*)(&temp240));
  stream_11(0, (void*)(&temp240));
  stream_13(0, (void*)(&temp240));
  stream_15(0, (void*)(&temp240));
  stream_17(0, (void*)(&temp240));
  stream_7(0, (void*)(&temp247));
  stream_9(0, (void*)(&temp247));
  stream_11(0, (void*)(&temp247));
  stream_13(0, (void*)(&temp247));
  stream_15(0, (void*)(&temp247));
  stream_17(0, (void*)(&temp247));
  stream_7(0, (void*)(&temp254));
  stream_9(0, (void*)(&temp254));
  stream_11(0, (void*)(&temp254));
  stream_13(0, (void*)(&temp254));
  stream_15(0, (void*)(&temp254));
  stream_17(0, (void*)(&temp254));
  stream_7(0, (void*)(&temp261));
  stream_9(0, (void*)(&temp261));
  stream_11(0, (void*)(&temp261));
  stream_13(0, (void*)(&temp261));
  stream_15(0, (void*)(&temp261));
  stream_17(0, (void*)(&temp261));
  stream_7(0, (void*)(&temp268));
  stream_9(0, (void*)(&temp268));
  stream_11(0, (void*)(&temp268));
  stream_13(0, (void*)(&temp268));
  stream_15(0, (void*)(&temp268));
  stream_17(0, (void*)(&temp268));
  stream_7(0, (void*)(&temp275));
  stream_9(0, (void*)(&temp275));
  stream_11(0, (void*)(&temp275));
  stream_13(0, (void*)(&temp275));
  stream_15(0, (void*)(&temp275));
  stream_17(0, (void*)(&temp275));
  stream_7(0, (void*)(&temp282));
  stream_9(0, (void*)(&temp282));
  stream_11(0, (void*)(&temp282));
  stream_13(0, (void*)(&temp282));
  stream_15(0, (void*)(&temp282));
  stream_17(0, (void*)(&temp282));
  stream_7(0, (void*)(&temp289));
  stream_9(0, (void*)(&temp289));
  stream_11(0, (void*)(&temp289));
  stream_13(0, (void*)(&temp289));
  stream_15(0, (void*)(&temp289));
  stream_17(0, (void*)(&temp289));
  stream_7(0, (void*)(&temp296));
  stream_9(0, (void*)(&temp296));
  stream_11(0, (void*)(&temp296));
  stream_13(0, (void*)(&temp296));
  stream_15(0, (void*)(&temp296));
  stream_17(0, (void*)(&temp296));
}

static void stream_11(uint8_t arg, void* value) {
  static struct tuple6 input_0;
  switch (arg) {
    case 0:
      input_0 = *((struct tuple6*)value);
      break;
  }
  stream_12(0, (void*)(&*((bool*)input_0.value2)));
}

static void stream_13(uint8_t arg, void* value) {
  static struct tuple6 input_0;
  switch (arg) {
    case 0:
      input_0 = *((struct tuple6*)value);
      break;
  }
  stream_14(0, (void*)(&*((bool*)input_0.value3)));
}

static void stream_15(uint8_t arg, void* value) {
  static struct tuple6 input_0;
  switch (arg) {
    case 0:
      input_0 = *((struct tuple6*)value);
      break;
  }
  stream_16(0, (void*)(&*((bool*)input_0.value4)));
}

static void stream_17(uint8_t arg, void* value) {
  static struct tuple6 input_0;
  switch (arg) {
    case 0:
      input_0 = *((struct tuple6*)value);
      break;
  }
  stream_18(0, (void*)(&*((uint16_t*)input_0.value5)));
}

static void stream_5(uint8_t arg, void* value) {
  static bool input_0;
  switch (arg) {
    case 0:
      input_0 = *((bool*)value);
      break;
  }
  if (input_0) {
    PORTB |= (1 << PB5);
  } else {
    PORTB &= ~(1 << PB5);
  }
}

static void stream_7(uint8_t arg, void* value) {
  static struct tuple6 input_0;
  switch (arg) {
    case 0:
      input_0 = *((struct tuple6*)value);
      break;
  }
  stream_8(0, (void*)(&*((bool*)input_0.value0)));
}

static void stream_9(uint8_t arg, void* value) {
  static struct tuple6 input_0;
  switch (arg) {
    case 0:
      input_0 = *((struct tuple6*)value);
      break;
  }
  stream_10(0, (void*)(&*((bool*)input_0.value1)));
}

static void stream_10(uint8_t arg, void* value) {
  static bool input_0;
  switch (arg) {
    case 0:
      input_0 = *((bool*)value);
      break;
  }
  if (input_0) {
    PORTB |= (1 << PB0);
  } else {
    PORTB &= ~(1 << PB0);
  }
}

static void stream_12(uint8_t arg, void* value) {
  static bool input_0;
  switch (arg) {
    case 0:
      input_0 = *((bool*)value);
      break;
  }
  if (input_0) {
    PORTD |= (1 << PD7);
  } else {
    PORTD &= ~(1 << PD7);
  }
}

static void stream_14(uint8_t arg, void* value) {
  static bool input_0;
  switch (arg) {
    case 0:
      input_0 = *((bool*)value);
      break;
  }
  if (input_0) {
    PORTD |= (1 << PD6);
  } else {
    PORTD &= ~(1 << PD6);
  }
}

static void stream_16(uint8_t arg, void* value) {
  static bool input_0;
  switch (arg) {
    case 0:
      input_0 = *((bool*)value);
      break;
  }
  if (input_0) {
    PORTD |= (1 << PD5);
  } else {
    PORTD &= ~(1 << PD5);
  }
}

static void stream_18(uint8_t arg, void* value) {
  bool temp297;
  uint16_t temp298;
  struct tuple2 temp299;
  bool temp300;
  uint16_t temp301;
  struct tuple2 temp302;
  static uint16_t input_0;
  switch (arg) {
    case 0:
      input_0 = *((uint16_t*)value);
      break;
  }
  temp297 = true;
  temp298 = 1;
  temp299.value0 = (void*)&temp297;
  temp299.value1 = (void*)&temp298;
  temp300 = false;
  temp301 = input_0;
  temp302.value0 = (void*)&temp300;
  temp302.value1 = (void*)&temp301;
  stream_19(0, (void*)(&temp299));
  stream_19(0, (void*)(&temp302));
}

static void stream_8(uint8_t arg, void* value) {
  static bool input_0;
  switch (arg) {
    case 0:
      input_0 = *((bool*)value);
      break;
  }
  if (input_0) {
    PORTD |= (1 << PD3);
  } else {
    PORTD &= ~(1 << PD3);
  }
}

static void stream_19(uint8_t arg, void* value) {
  static struct tuple2 input_0;
  switch (arg) {
    case 0:
      input_0 = *((struct tuple2*)value);
      break;
  }
  stream_20(0, (void*)(&*((bool*)input_0.value0)));
  // Delay assumes a 16MHz clock
  _delay_loop_2(*((uint16_t*)input_0.value1));
  _delay_loop_2(*((uint16_t*)input_0.value1));
  _delay_loop_2(*((uint16_t*)input_0.value1));
  _delay_loop_2(*((uint16_t*)input_0.value1));
}

static void stream_20(uint8_t arg, void* value) {
  static bool input_0;
  switch (arg) {
    case 0:
      input_0 = *((bool*)value);
      break;
  }
  if (input_0) {
    PORTD |= (1 << PD4);
  } else {
    PORTD &= ~(1 << PD4);
  }
}

int main(void) {
  TCCR1B |= (1 << CS12);
  TCCR1B |= (1 << CS10);
  DDRB |= (1 << PB0);
  DDRD |= (1 << PD7);
  DDRD |= (1 << PD6);
  DDRD |= (1 << PD5);
  DDRD |= (1 << PD4);
  DDRB |= (1 << PB5);
  DDRD |= (1 << PD3);
  while (1) {
    input_timer();
  }
  return 0;
}
