// This file is automatically generated.

#include <avr/io.h>
#include <util/delay_basic.h>
#include <stdbool.h>

struct list {
    uint8_t size;
    void* values;
};

struct tuple2 {
    void* value0;
    void* value1;
};

struct tuple6 {
    void* value0;
    void* value1;
    void* value2;
    void* value3;
    void* value4;
    void* value5;
};

static void bootup();

static void input_timer();

static void stream_1(uint8_t arg, void* value);

static void stream_6(uint8_t arg, void* value);

static void stream_2(uint8_t arg, void* value);

static void stream_3(uint8_t arg, void* value);

static void stream_4(uint8_t arg, void* value);

static void stream_7(uint8_t arg, void* value);

static void stream_5(uint8_t arg, void* value);

static void stream_8(uint8_t arg, void* value);

static void stream_11(uint8_t arg, void* value);

static void stream_13(uint8_t arg, void* value);

static void stream_15(uint8_t arg, void* value);

static void stream_17(uint8_t arg, void* value);

static void stream_19(uint8_t arg, void* value);

static void stream_9(uint8_t arg, void* value);

static void stream_10(uint8_t arg, void* value);

static void stream_12(uint8_t arg, void* value);

static void stream_14(uint8_t arg, void* value);

static void stream_16(uint8_t arg, void* value);

static void stream_18(uint8_t arg, void* value);

static void stream_20(uint8_t arg, void* value);

static void stream_21(uint8_t arg, void* value);

static void stream_22(uint8_t arg, void* value);

static void bootup() {
  bool temp0;
  temp0 = 0;
  stream_6(0, (void*)(&temp0));
}

static void input_timer() {
  uint16_t temp1;
  temp1 = TCNT1;
  TCNT1 = 0;
  stream_1(0, (void*)(&temp1));
}

static void stream_1(uint8_t arg, void* value) {
  uint16_t input_0 = *((uint16_t*)value);
  static uint16_t input_1 = 0;
  uint16_t temp2;
  if ((input_1 > 10000)) {
    temp2 = ((input_1 - 10000) + input_0);
  } else {
    temp2 = (input_1 + input_0);
  }
  input_1 = temp2;
  stream_2(0, (void*)(&input_1));
}

static void stream_6(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  bool temp3;
  bool temp4;
  bool temp5;
  bool temp6;
  bool temp7;
  uint16_t temp8;
  struct tuple6 temp9;
  bool temp10;
  bool temp11;
  bool temp12;
  bool temp13;
  bool temp14;
  uint16_t temp15;
  struct tuple6 temp16;
  bool temp17;
  bool temp18;
  bool temp19;
  bool temp20;
  bool temp21;
  uint16_t temp22;
  struct tuple6 temp23;
  bool temp24;
  bool temp25;
  bool temp26;
  bool temp27;
  bool temp28;
  uint16_t temp29;
  struct tuple6 temp30;
  bool temp31;
  bool temp32;
  bool temp33;
  bool temp34;
  bool temp35;
  uint16_t temp36;
  struct tuple6 temp37;
  bool temp38;
  bool temp39;
  bool temp40;
  bool temp41;
  bool temp42;
  uint16_t temp43;
  struct tuple6 temp44;
  bool temp45;
  bool temp46;
  bool temp47;
  bool temp48;
  bool temp49;
  uint16_t temp50;
  struct tuple6 temp51;
  bool temp52;
  bool temp53;
  bool temp54;
  bool temp55;
  bool temp56;
  uint16_t temp57;
  struct tuple6 temp58;
  bool temp59;
  bool temp60;
  bool temp61;
  bool temp62;
  bool temp63;
  uint16_t temp64;
  struct tuple6 temp65;
  bool temp66;
  bool temp67;
  bool temp68;
  bool temp69;
  bool temp70;
  uint16_t temp71;
  struct tuple6 temp72;
  bool temp73;
  bool temp74;
  bool temp75;
  bool temp76;
  bool temp77;
  uint16_t temp78;
  struct tuple6 temp79;
  bool temp80;
  bool temp81;
  bool temp82;
  bool temp83;
  bool temp84;
  uint16_t temp85;
  struct tuple6 temp86;
  bool temp87;
  bool temp88;
  bool temp89;
  bool temp90;
  bool temp91;
  uint16_t temp92;
  struct tuple6 temp93;
  bool temp94;
  bool temp95;
  bool temp96;
  bool temp97;
  bool temp98;
  uint16_t temp99;
  struct tuple6 temp100;
  temp3 = false;
  temp4 = false;
  temp5 = false;
  temp6 = true;
  temp7 = true;
  temp8 = 5600;
  temp9.value0 = (void*)&temp3;
  temp9.value1 = (void*)&temp4;
  temp9.value2 = (void*)&temp5;
  temp9.value3 = (void*)&temp6;
  temp9.value4 = (void*)&temp7;
  temp9.value5 = (void*)&temp8;
  temp10 = false;
  temp11 = false;
  temp12 = false;
  temp13 = true;
  temp14 = true;
  temp15 = 5600;
  temp16.value0 = (void*)&temp10;
  temp16.value1 = (void*)&temp11;
  temp16.value2 = (void*)&temp12;
  temp16.value3 = (void*)&temp13;
  temp16.value4 = (void*)&temp14;
  temp16.value5 = (void*)&temp15;
  temp17 = false;
  temp18 = false;
  temp19 = false;
  temp20 = true;
  temp21 = true;
  temp22 = 250;
  temp23.value0 = (void*)&temp17;
  temp23.value1 = (void*)&temp18;
  temp23.value2 = (void*)&temp19;
  temp23.value3 = (void*)&temp20;
  temp23.value4 = (void*)&temp21;
  temp23.value5 = (void*)&temp22;
  temp24 = false;
  temp25 = false;
  temp26 = false;
  temp27 = true;
  temp28 = false;
  temp29 = 100;
  temp30.value0 = (void*)&temp24;
  temp30.value1 = (void*)&temp25;
  temp30.value2 = (void*)&temp26;
  temp30.value3 = (void*)&temp27;
  temp30.value4 = (void*)&temp28;
  temp30.value5 = (void*)&temp29;
  temp31 = false;
  temp32 = false;
  temp33 = false;
  temp34 = true;
  temp35 = false;
  temp36 = 100;
  temp37.value0 = (void*)&temp31;
  temp37.value1 = (void*)&temp32;
  temp37.value2 = (void*)&temp33;
  temp37.value3 = (void*)&temp34;
  temp37.value4 = (void*)&temp35;
  temp37.value5 = (void*)&temp36;
  temp38 = false;
  temp39 = true;
  temp40 = false;
  temp41 = false;
  temp42 = false;
  temp43 = 100;
  temp44.value0 = (void*)&temp38;
  temp44.value1 = (void*)&temp39;
  temp44.value2 = (void*)&temp40;
  temp44.value3 = (void*)&temp41;
  temp44.value4 = (void*)&temp42;
  temp44.value5 = (void*)&temp43;
  temp45 = false;
  temp46 = false;
  temp47 = false;
  temp48 = false;
  temp49 = false;
  temp50 = 100;
  temp51.value0 = (void*)&temp45;
  temp51.value1 = (void*)&temp46;
  temp51.value2 = (void*)&temp47;
  temp51.value3 = (void*)&temp48;
  temp51.value4 = (void*)&temp49;
  temp51.value5 = (void*)&temp50;
  temp52 = false;
  temp53 = true;
  temp54 = false;
  temp55 = false;
  temp56 = false;
  temp57 = 100;
  temp58.value0 = (void*)&temp52;
  temp58.value1 = (void*)&temp53;
  temp58.value2 = (void*)&temp54;
  temp58.value3 = (void*)&temp55;
  temp58.value4 = (void*)&temp56;
  temp58.value5 = (void*)&temp57;
  temp59 = false;
  temp60 = false;
  temp61 = false;
  temp62 = false;
  temp63 = false;
  temp64 = 100;
  temp65.value0 = (void*)&temp59;
  temp65.value1 = (void*)&temp60;
  temp65.value2 = (void*)&temp61;
  temp65.value3 = (void*)&temp62;
  temp65.value4 = (void*)&temp63;
  temp65.value5 = (void*)&temp64;
  temp66 = false;
  temp67 = false;
  temp68 = false;
  temp69 = false;
  temp70 = true;
  temp71 = 2100;
  temp72.value0 = (void*)&temp66;
  temp72.value1 = (void*)&temp67;
  temp72.value2 = (void*)&temp68;
  temp72.value3 = (void*)&temp69;
  temp72.value4 = (void*)&temp70;
  temp72.value5 = (void*)&temp71;
  temp73 = false;
  temp74 = false;
  temp75 = false;
  temp76 = false;
  temp77 = false;
  temp78 = 100;
  temp79.value0 = (void*)&temp73;
  temp79.value1 = (void*)&temp74;
  temp79.value2 = (void*)&temp75;
  temp79.value3 = (void*)&temp76;
  temp79.value4 = (void*)&temp77;
  temp79.value5 = (void*)&temp78;
  temp80 = false;
  temp81 = false;
  temp82 = true;
  temp83 = true;
  temp84 = false;
  temp85 = 100;
  temp86.value0 = (void*)&temp80;
  temp86.value1 = (void*)&temp81;
  temp86.value2 = (void*)&temp82;
  temp86.value3 = (void*)&temp83;
  temp86.value4 = (void*)&temp84;
  temp86.value5 = (void*)&temp85;
  temp87 = false;
  temp88 = false;
  temp89 = false;
  temp90 = false;
  temp91 = false;
  temp92 = 100;
  temp93.value0 = (void*)&temp87;
  temp93.value1 = (void*)&temp88;
  temp93.value2 = (void*)&temp89;
  temp93.value3 = (void*)&temp90;
  temp93.value4 = (void*)&temp91;
  temp93.value5 = (void*)&temp92;
  temp94 = false;
  temp95 = true;
  temp96 = true;
  temp97 = true;
  temp98 = true;
  temp99 = 100;
  temp100.value0 = (void*)&temp94;
  temp100.value1 = (void*)&temp95;
  temp100.value2 = (void*)&temp96;
  temp100.value3 = (void*)&temp97;
  temp100.value4 = (void*)&temp98;
  temp100.value5 = (void*)&temp99;
  stream_8(0, (void*)(&temp9));
  stream_8(0, (void*)(&temp16));
  stream_8(0, (void*)(&temp23));
  stream_8(0, (void*)(&temp30));
  stream_8(0, (void*)(&temp37));
  stream_8(0, (void*)(&temp44));
  stream_8(0, (void*)(&temp51));
  stream_8(0, (void*)(&temp58));
  stream_8(0, (void*)(&temp65));
  stream_8(0, (void*)(&temp72));
  stream_8(0, (void*)(&temp79));
  stream_8(0, (void*)(&temp86));
  stream_8(0, (void*)(&temp93));
  stream_8(0, (void*)(&temp100));
}

static void stream_2(uint8_t arg, void* value) {
  uint16_t input_0 = *((uint16_t*)value);
  if ((input_0 > 10000)) {
    stream_3(0, (void*)(&input_0));
  }
}

static void stream_3(uint8_t arg, void* value) {
  uint16_t input_0 = *((uint16_t*)value);
  static uint16_t input_1 = 0;
  input_1 = (input_1 + 1);
  stream_4(0, (void*)(&input_1));
  stream_7(0, (void*)(&input_1));
}

static void stream_4(uint8_t arg, void* value) {
  uint16_t input_0 = *((uint16_t*)value);
  bool temp101;
  temp101 = (input_0) % 2 == 0;
  stream_5(0, (void*)(&temp101));
}

static void stream_7(uint8_t arg, void* value) {
  uint16_t input_0 = *((uint16_t*)value);
  bool temp102;
  bool temp103;
  bool temp104;
  bool temp105;
  bool temp106;
  uint16_t temp107;
  struct tuple6 temp108;
  bool temp109;
  bool temp110;
  bool temp111;
  bool temp112;
  bool temp113;
  uint16_t temp114;
  struct tuple6 temp115;
  bool temp116;
  bool temp117;
  bool temp118;
  bool temp119;
  bool temp120;
  uint16_t temp121;
  struct tuple6 temp122;
  bool temp123;
  bool temp124;
  bool temp125;
  bool temp126;
  bool temp127;
  uint16_t temp128;
  struct tuple6 temp129;
  bool temp130;
  bool temp131;
  bool temp132;
  bool temp133;
  bool temp134;
  uint16_t temp135;
  struct tuple6 temp136;
  bool temp137;
  bool temp138;
  bool temp139;
  bool temp140;
  bool temp141;
  uint16_t temp142;
  struct tuple6 temp143;
  bool temp144;
  bool temp145;
  bool temp146;
  bool temp147;
  bool temp148;
  uint16_t temp149;
  struct tuple6 temp150;
  bool temp151;
  bool temp152;
  bool temp153;
  bool temp154;
  bool temp155;
  uint16_t temp156;
  struct tuple6 temp157;
  bool temp158;
  bool temp159;
  bool temp160;
  bool temp161;
  bool temp162;
  uint16_t temp163;
  struct tuple6 temp164;
  bool temp165;
  bool temp166;
  bool temp167;
  bool temp168;
  bool temp169;
  uint16_t temp170;
  struct tuple6 temp171;
  bool temp172;
  bool temp173;
  bool temp174;
  bool temp175;
  bool temp176;
  uint16_t temp177;
  struct tuple6 temp178;
  bool temp179;
  bool temp180;
  bool temp181;
  bool temp182;
  bool temp183;
  uint16_t temp184;
  struct tuple6 temp185;
  bool temp186;
  bool temp187;
  bool temp188;
  bool temp189;
  bool temp190;
  uint16_t temp191;
  struct tuple6 temp192;
  bool temp193;
  bool temp194;
  bool temp195;
  bool temp196;
  bool temp197;
  uint16_t temp198;
  struct tuple6 temp199;
  bool temp200;
  bool temp201;
  bool temp202;
  bool temp203;
  bool temp204;
  uint16_t temp205;
  struct tuple6 temp206;
  bool temp207;
  bool temp208;
  bool temp209;
  bool temp210;
  bool temp211;
  uint16_t temp212;
  struct tuple6 temp213;
  bool temp214;
  bool temp215;
  bool temp216;
  bool temp217;
  bool temp218;
  uint16_t temp219;
  struct tuple6 temp220;
  bool temp221;
  bool temp222;
  bool temp223;
  bool temp224;
  bool temp225;
  uint16_t temp226;
  struct tuple6 temp227;
  bool temp228;
  bool temp229;
  bool temp230;
  bool temp231;
  bool temp232;
  uint16_t temp233;
  struct tuple6 temp234;
  bool temp235;
  bool temp236;
  bool temp237;
  bool temp238;
  bool temp239;
  uint16_t temp240;
  struct tuple6 temp241;
  bool temp242;
  bool temp243;
  bool temp244;
  bool temp245;
  bool temp246;
  uint16_t temp247;
  struct tuple6 temp248;
  bool temp249;
  bool temp250;
  bool temp251;
  bool temp252;
  bool temp253;
  uint16_t temp254;
  struct tuple6 temp255;
  bool temp256;
  bool temp257;
  bool temp258;
  bool temp259;
  bool temp260;
  uint16_t temp261;
  struct tuple6 temp262;
  bool temp263;
  bool temp264;
  bool temp265;
  bool temp266;
  bool temp267;
  uint16_t temp268;
  struct tuple6 temp269;
  bool temp270;
  bool temp271;
  bool temp272;
  bool temp273;
  bool temp274;
  uint16_t temp275;
  struct tuple6 temp276;
  bool temp277;
  bool temp278;
  bool temp279;
  bool temp280;
  bool temp281;
  uint16_t temp282;
  struct tuple6 temp283;
  bool temp284;
  bool temp285;
  bool temp286;
  bool temp287;
  bool temp288;
  uint16_t temp289;
  struct tuple6 temp290;
  bool temp291;
  bool temp292;
  bool temp293;
  bool temp294;
  bool temp295;
  uint16_t temp296;
  struct tuple6 temp297;
  bool temp298;
  bool temp299;
  bool temp300;
  bool temp301;
  bool temp302;
  uint16_t temp303;
  struct tuple6 temp304;
  bool temp305;
  bool temp306;
  bool temp307;
  bool temp308;
  bool temp309;
  uint16_t temp310;
  struct tuple6 temp311;
  temp102 = false;
  temp103 = true;
  temp104 = false;
  temp105 = false;
  temp106 = false;
  temp107 = 100;
  temp108.value0 = (void*)&temp102;
  temp108.value1 = (void*)&temp103;
  temp108.value2 = (void*)&temp104;
  temp108.value3 = (void*)&temp105;
  temp108.value4 = (void*)&temp106;
  temp108.value5 = (void*)&temp107;
  temp109 = false;
  temp110 = false;
  temp111 = false;
  temp112 = false;
  temp113 = false;
  temp114 = 100;
  temp115.value0 = (void*)&temp109;
  temp115.value1 = (void*)&temp110;
  temp115.value2 = (void*)&temp111;
  temp115.value3 = (void*)&temp112;
  temp115.value4 = (void*)&temp113;
  temp115.value5 = (void*)&temp114;
  temp116 = true;
  temp117 = false;
  temp118 = true;
  temp119 = false;
  temp120 = false;
  temp121 = 100;
  temp122.value0 = (void*)&temp116;
  temp122.value1 = (void*)&temp117;
  temp122.value2 = (void*)&temp118;
  temp122.value3 = (void*)&temp119;
  temp122.value4 = (void*)&temp120;
  temp122.value5 = (void*)&temp121;
  temp123 = true;
  temp124 = false;
  temp125 = true;
  temp126 = true;
  temp127 = false;
  temp128 = 100;
  temp129.value0 = (void*)&temp123;
  temp129.value1 = (void*)&temp124;
  temp129.value2 = (void*)&temp125;
  temp129.value3 = (void*)&temp126;
  temp129.value4 = (void*)&temp127;
  temp129.value5 = (void*)&temp128;
  temp130 = true;
  temp131 = false;
  temp132 = true;
  temp133 = false;
  temp134 = true;
  temp135 = 100;
  temp136.value0 = (void*)&temp130;
  temp136.value1 = (void*)&temp131;
  temp136.value2 = (void*)&temp132;
  temp136.value3 = (void*)&temp133;
  temp136.value4 = (void*)&temp134;
  temp136.value5 = (void*)&temp135;
  temp137 = true;
  temp138 = false;
  temp139 = false;
  temp140 = true;
  temp141 = false;
  temp142 = 100;
  temp143.value0 = (void*)&temp137;
  temp143.value1 = (void*)&temp138;
  temp143.value2 = (void*)&temp139;
  temp143.value3 = (void*)&temp140;
  temp143.value4 = (void*)&temp141;
  temp143.value5 = (void*)&temp142;
  temp144 = true;
  temp145 = false;
  temp146 = true;
  temp147 = false;
  temp148 = true;
  temp149 = 100;
  temp150.value0 = (void*)&temp144;
  temp150.value1 = (void*)&temp145;
  temp150.value2 = (void*)&temp146;
  temp150.value3 = (void*)&temp147;
  temp150.value4 = (void*)&temp148;
  temp150.value5 = (void*)&temp149;
  temp151 = true;
  temp152 = false;
  temp153 = false;
  temp154 = false;
  temp155 = false;
  temp156 = 100;
  temp157.value0 = (void*)&temp151;
  temp157.value1 = (void*)&temp152;
  temp157.value2 = (void*)&temp153;
  temp157.value3 = (void*)&temp154;
  temp157.value4 = (void*)&temp155;
  temp157.value5 = (void*)&temp156;
  temp158 = true;
  temp159 = false;
  temp160 = false;
  temp161 = true;
  temp162 = false;
  temp163 = 100;
  temp164.value0 = (void*)&temp158;
  temp164.value1 = (void*)&temp159;
  temp164.value2 = (void*)&temp160;
  temp164.value3 = (void*)&temp161;
  temp164.value4 = (void*)&temp162;
  temp164.value5 = (void*)&temp163;
  temp165 = true;
  temp166 = false;
  temp167 = false;
  temp168 = false;
  temp169 = false;
  temp170 = 100;
  temp171.value0 = (void*)&temp165;
  temp171.value1 = (void*)&temp166;
  temp171.value2 = (void*)&temp167;
  temp171.value3 = (void*)&temp168;
  temp171.value4 = (void*)&temp169;
  temp171.value5 = (void*)&temp170;
  temp172 = true;
  temp173 = false;
  temp174 = true;
  temp175 = false;
  temp176 = false;
  temp177 = 100;
  temp178.value0 = (void*)&temp172;
  temp178.value1 = (void*)&temp173;
  temp178.value2 = (void*)&temp174;
  temp178.value3 = (void*)&temp175;
  temp178.value4 = (void*)&temp176;
  temp178.value5 = (void*)&temp177;
  temp179 = true;
  temp180 = false;
  temp181 = false;
  temp182 = false;
  temp183 = true;
  temp184 = 100;
  temp185.value0 = (void*)&temp179;
  temp185.value1 = (void*)&temp180;
  temp185.value2 = (void*)&temp181;
  temp185.value3 = (void*)&temp182;
  temp185.value4 = (void*)&temp183;
  temp185.value5 = (void*)&temp184;
  temp186 = true;
  temp187 = false;
  temp188 = true;
  temp189 = true;
  temp190 = true;
  temp191 = 100;
  temp192.value0 = (void*)&temp186;
  temp192.value1 = (void*)&temp187;
  temp192.value2 = (void*)&temp188;
  temp192.value3 = (void*)&temp189;
  temp192.value4 = (void*)&temp190;
  temp192.value5 = (void*)&temp191;
  temp193 = true;
  temp194 = false;
  temp195 = false;
  temp196 = true;
  temp197 = false;
  temp198 = 100;
  temp199.value0 = (void*)&temp193;
  temp199.value1 = (void*)&temp194;
  temp199.value2 = (void*)&temp195;
  temp199.value3 = (void*)&temp196;
  temp199.value4 = (void*)&temp197;
  temp199.value5 = (void*)&temp198;
  temp200 = true;
  temp201 = false;
  temp202 = true;
  temp203 = true;
  temp204 = false;
  temp205 = 100;
  temp206.value0 = (void*)&temp200;
  temp206.value1 = (void*)&temp201;
  temp206.value2 = (void*)&temp202;
  temp206.value3 = (void*)&temp203;
  temp206.value4 = (void*)&temp204;
  temp206.value5 = (void*)&temp205;
  temp207 = true;
  temp208 = false;
  temp209 = true;
  temp210 = false;
  temp211 = false;
  temp212 = 100;
  temp213.value0 = (void*)&temp207;
  temp213.value1 = (void*)&temp208;
  temp213.value2 = (void*)&temp209;
  temp213.value3 = (void*)&temp210;
  temp213.value4 = (void*)&temp211;
  temp213.value5 = (void*)&temp212;
  temp214 = true;
  temp215 = false;
  temp216 = true;
  temp217 = true;
  temp218 = true;
  temp219 = 100;
  temp220.value0 = (void*)&temp214;
  temp220.value1 = (void*)&temp215;
  temp220.value2 = (void*)&temp216;
  temp220.value3 = (void*)&temp217;
  temp220.value4 = (void*)&temp218;
  temp220.value5 = (void*)&temp219;
  temp221 = true;
  temp222 = false;
  temp223 = true;
  temp224 = false;
  temp225 = true;
  temp226 = 100;
  temp227.value0 = (void*)&temp221;
  temp227.value1 = (void*)&temp222;
  temp227.value2 = (void*)&temp223;
  temp227.value3 = (void*)&temp224;
  temp227.value4 = (void*)&temp225;
  temp227.value5 = (void*)&temp226;
  temp228 = true;
  temp229 = false;
  temp230 = true;
  temp231 = true;
  temp232 = false;
  temp233 = 100;
  temp234.value0 = (void*)&temp228;
  temp234.value1 = (void*)&temp229;
  temp234.value2 = (void*)&temp230;
  temp234.value3 = (void*)&temp231;
  temp234.value4 = (void*)&temp232;
  temp234.value5 = (void*)&temp233;
  temp235 = true;
  temp236 = true;
  temp237 = false;
  temp238 = false;
  temp239 = true;
  temp240 = 100;
  temp241.value0 = (void*)&temp235;
  temp241.value1 = (void*)&temp236;
  temp241.value2 = (void*)&temp237;
  temp241.value3 = (void*)&temp238;
  temp241.value4 = (void*)&temp239;
  temp241.value5 = (void*)&temp240;
  temp242 = true;
  temp243 = false;
  temp244 = true;
  temp245 = true;
  temp246 = false;
  temp247 = 100;
  temp248.value0 = (void*)&temp242;
  temp248.value1 = (void*)&temp243;
  temp248.value2 = (void*)&temp244;
  temp248.value3 = (void*)&temp245;
  temp248.value4 = (void*)&temp246;
  temp248.value5 = (void*)&temp247;
  temp249 = true;
  temp250 = true;
  temp251 = true;
  temp252 = true;
  temp253 = false;
  temp254 = 100;
  temp255.value0 = (void*)&temp249;
  temp255.value1 = (void*)&temp250;
  temp255.value2 = (void*)&temp251;
  temp255.value3 = (void*)&temp252;
  temp255.value4 = (void*)&temp253;
  temp255.value5 = (void*)&temp254;
  temp256 = true;
  temp257 = false;
  temp258 = true;
  temp259 = true;
  temp260 = false;
  temp261 = 100;
  temp262.value0 = (void*)&temp256;
  temp262.value1 = (void*)&temp257;
  temp262.value2 = (void*)&temp258;
  temp262.value3 = (void*)&temp259;
  temp262.value4 = (void*)&temp260;
  temp262.value5 = (void*)&temp261;
  temp263 = true;
  temp264 = true;
  temp265 = true;
  temp266 = true;
  temp267 = true;
  temp268 = 100;
  temp269.value0 = (void*)&temp263;
  temp269.value1 = (void*)&temp264;
  temp269.value2 = (void*)&temp265;
  temp269.value3 = (void*)&temp266;
  temp269.value4 = (void*)&temp267;
  temp269.value5 = (void*)&temp268;
  temp270 = true;
  temp271 = false;
  temp272 = false;
  temp273 = true;
  temp274 = false;
  temp275 = 100;
  temp276.value0 = (void*)&temp270;
  temp276.value1 = (void*)&temp271;
  temp276.value2 = (void*)&temp272;
  temp276.value3 = (void*)&temp273;
  temp276.value4 = (void*)&temp274;
  temp276.value5 = (void*)&temp275;
  temp277 = true;
  temp278 = false;
  temp279 = false;
  temp280 = false;
  temp281 = false;
  temp282 = 100;
  temp283.value0 = (void*)&temp277;
  temp283.value1 = (void*)&temp278;
  temp283.value2 = (void*)&temp279;
  temp283.value3 = (void*)&temp280;
  temp283.value4 = (void*)&temp281;
  temp283.value5 = (void*)&temp282;
  temp284 = true;
  temp285 = false;
  temp286 = false;
  temp287 = true;
  temp288 = true;
  temp289 = 100;
  temp290.value0 = (void*)&temp284;
  temp290.value1 = (void*)&temp285;
  temp290.value2 = (void*)&temp286;
  temp290.value3 = (void*)&temp287;
  temp290.value4 = (void*)&temp288;
  temp290.value5 = (void*)&temp289;
  temp291 = true;
  temp292 = true;
  temp293 = false;
  temp294 = true;
  temp295 = false;
  temp296 = 100;
  temp297.value0 = (void*)&temp291;
  temp297.value1 = (void*)&temp292;
  temp297.value2 = (void*)&temp293;
  temp297.value3 = (void*)&temp294;
  temp297.value4 = (void*)&temp295;
  temp297.value5 = (void*)&temp296;
  temp298 = true;
  temp299 = false;
  temp300 = false;
  temp301 = true;
  temp302 = false;
  temp303 = 100;
  temp304.value0 = (void*)&temp298;
  temp304.value1 = (void*)&temp299;
  temp304.value2 = (void*)&temp300;
  temp304.value3 = (void*)&temp301;
  temp304.value4 = (void*)&temp302;
  temp304.value5 = (void*)&temp303;
  temp305 = true;
  temp306 = true;
  temp307 = false;
  temp308 = false;
  temp309 = true;
  temp310 = 100;
  temp311.value0 = (void*)&temp305;
  temp311.value1 = (void*)&temp306;
  temp311.value2 = (void*)&temp307;
  temp311.value3 = (void*)&temp308;
  temp311.value4 = (void*)&temp309;
  temp311.value5 = (void*)&temp310;
  stream_8(1, (void*)(&temp108));
  stream_8(1, (void*)(&temp115));
  stream_8(1, (void*)(&temp122));
  stream_8(1, (void*)(&temp129));
  stream_8(1, (void*)(&temp136));
  stream_8(1, (void*)(&temp143));
  stream_8(1, (void*)(&temp150));
  stream_8(1, (void*)(&temp157));
  stream_8(1, (void*)(&temp164));
  stream_8(1, (void*)(&temp171));
  stream_8(1, (void*)(&temp178));
  stream_8(1, (void*)(&temp185));
  stream_8(1, (void*)(&temp192));
  stream_8(1, (void*)(&temp199));
  stream_8(1, (void*)(&temp206));
  stream_8(1, (void*)(&temp213));
  stream_8(1, (void*)(&temp220));
  stream_8(1, (void*)(&temp227));
  stream_8(1, (void*)(&temp234));
  stream_8(1, (void*)(&temp241));
  stream_8(1, (void*)(&temp248));
  stream_8(1, (void*)(&temp255));
  stream_8(1, (void*)(&temp262));
  stream_8(1, (void*)(&temp269));
  stream_8(1, (void*)(&temp276));
  stream_8(1, (void*)(&temp283));
  stream_8(1, (void*)(&temp290));
  stream_8(1, (void*)(&temp297));
  stream_8(1, (void*)(&temp304));
  stream_8(1, (void*)(&temp311));
}

static void stream_5(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  if (input_0) {
    PORTB |= (1 << PB5);
  } else {
    PORTB &= ~(1 << PB5);
  }
}

static void stream_8(uint8_t arg, void* value) {
  struct tuple6 input_0 = *((struct tuple6*)value);
  stream_9(0, (void*)(&input_0));
  stream_11(0, (void*)(&input_0));
  stream_13(0, (void*)(&input_0));
  stream_15(0, (void*)(&input_0));
  stream_17(0, (void*)(&input_0));
  stream_19(0, (void*)(&input_0));
}

static void stream_11(uint8_t arg, void* value) {
  struct tuple6 input_0 = *((struct tuple6*)value);
  stream_12(0, (void*)(&*((bool*)input_0.value1)));
}

static void stream_13(uint8_t arg, void* value) {
  struct tuple6 input_0 = *((struct tuple6*)value);
  stream_14(0, (void*)(&*((bool*)input_0.value2)));
}

static void stream_15(uint8_t arg, void* value) {
  struct tuple6 input_0 = *((struct tuple6*)value);
  stream_16(0, (void*)(&*((bool*)input_0.value3)));
}

static void stream_17(uint8_t arg, void* value) {
  struct tuple6 input_0 = *((struct tuple6*)value);
  stream_18(0, (void*)(&*((bool*)input_0.value4)));
}

static void stream_19(uint8_t arg, void* value) {
  struct tuple6 input_0 = *((struct tuple6*)value);
  stream_20(0, (void*)(&*((uint16_t*)input_0.value5)));
}

static void stream_9(uint8_t arg, void* value) {
  struct tuple6 input_0 = *((struct tuple6*)value);
  stream_10(0, (void*)(&*((bool*)input_0.value0)));
}

static void stream_10(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  if (input_0) {
    PORTD |= (1 << PD3);
  } else {
    PORTD &= ~(1 << PD3);
  }
}

static void stream_12(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  if (input_0) {
    PORTB |= (1 << PB0);
  } else {
    PORTB &= ~(1 << PB0);
  }
}

static void stream_14(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  if (input_0) {
    PORTD |= (1 << PD7);
  } else {
    PORTD &= ~(1 << PD7);
  }
}

static void stream_16(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  if (input_0) {
    PORTD |= (1 << PD6);
  } else {
    PORTD &= ~(1 << PD6);
  }
}

static void stream_18(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  if (input_0) {
    PORTD |= (1 << PD5);
  } else {
    PORTD &= ~(1 << PD5);
  }
}

static void stream_20(uint8_t arg, void* value) {
  uint16_t input_0 = *((uint16_t*)value);
  bool temp312;
  uint16_t temp313;
  struct tuple2 temp314;
  bool temp315;
  uint16_t temp316;
  struct tuple2 temp317;
  temp312 = true;
  temp313 = 1;
  temp314.value0 = (void*)&temp312;
  temp314.value1 = (void*)&temp313;
  temp315 = false;
  temp316 = input_0;
  temp317.value0 = (void*)&temp315;
  temp317.value1 = (void*)&temp316;
  stream_21(0, (void*)(&temp314));
  stream_21(0, (void*)(&temp317));
}

static void stream_21(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  stream_22(0, (void*)(&*((bool*)input_0.value0)));
  // Delay assumes a 16MHz clock
  _delay_loop_2(*((uint16_t*)input_0.value1));
  _delay_loop_2(*((uint16_t*)input_0.value1));
  _delay_loop_2(*((uint16_t*)input_0.value1));
  _delay_loop_2(*((uint16_t*)input_0.value1));
}

static void stream_22(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  if (input_0) {
    PORTD |= (1 << PD4);
  } else {
    PORTD &= ~(1 << PD4);
  }
}

int main(void) {
  TCCR1B |= (1 << CS12);
  TCCR1B |= (1 << CS10);
  DDRD |= (1 << PD3);
  DDRB |= (1 << PB0);
  DDRD |= (1 << PD7);
  DDRD |= (1 << PD6);
  DDRD |= (1 << PD5);
  DDRD |= (1 << PD4);
  DDRB |= (1 << PB5);
  bootup();
  while (1) {
    input_timer();
  }
  return 0;
}
