// This file is automatically generated.

#include <avr/io.h>
#include <stdbool.h>

static void input_timer();

static void stream_1(int arg, void* value);

static void stream_6(int arg, void* value);

static void stream_2(int arg, void* value);

static void stream_7(int arg, void* value);

static void stream_3(int arg, void* value);

static void stream_8(int arg, void* value);

static void stream_4(int arg, void* value);

static void stream_9(int arg, void* value);

static void stream_10(int arg, void* value);

static void stream_5(int arg, void* value);

static void input_timer() {
  int temp0;
  temp0 = TCNT1;
  TCNT1 = 0;
  stream_1(0, (void*)(&temp0));
  stream_6(0, (void*)(&temp0));
}

static void stream_1(int arg, void* value) {
  static int input_0;
  switch (arg) {
    case 0:
      input_0 = *((int*)value);
      break;
  }
  static int fold_state = 0;
  bool temp1;
  temp1 = fold_state > 10000;
  int temp2;
  temp2 = input_0 + fold_state;
  int temp3;
  temp3 = temp2 - 10000;
  int temp4;
  temp4 = input_0 + fold_state;
  int temp5;
  if (temp1) {
    temp5 = temp3;
  } else {
    temp5 = temp4;
  }
  fold_state = temp5;
  stream_2(0, (void*)(&fold_state));
}

static void stream_6(int arg, void* value) {
  static int input_0;
  switch (arg) {
    case 0:
      input_0 = *((int*)value);
      break;
  }
  static int fold_state = 0;
  bool temp6;
  temp6 = fold_state > 10000;
  int temp7;
  temp7 = input_0 + fold_state;
  int temp8;
  temp8 = temp7 - 10000;
  int temp9;
  temp9 = input_0 + fold_state;
  int temp10;
  if (temp6) {
    temp10 = temp8;
  } else {
    temp10 = temp9;
  }
  fold_state = temp10;
  stream_7(0, (void*)(&fold_state));
}

static void stream_2(int arg, void* value) {
  static int input_0;
  switch (arg) {
    case 0:
      input_0 = *((int*)value);
      break;
  }
  bool temp11;
  temp11 = input_0 > 10000;
  bool temp12;
  temp12 = false;
  if (temp11) {
    temp12 = true;
  }
  if (temp12) {
    stream_3(0, (void*)(&input_0));
  }
}

static void stream_7(int arg, void* value) {
  static int input_0;
  switch (arg) {
    case 0:
      input_0 = *((int*)value);
      break;
  }
  bool temp13;
  temp13 = input_0 > 10000;
  bool temp14;
  temp14 = false;
  if (temp13) {
    temp14 = true;
  }
  if (temp14) {
    stream_8(0, (void*)(&input_0));
  }
}

static void stream_3(int arg, void* value) {
  static int input_0;
  switch (arg) {
    case 0:
      input_0 = *((int*)value);
      break;
  }
  static int fold_state = 0;
  int temp15;
  temp15 = fold_state + 1;
  fold_state = temp15;
  stream_4(0, (void*)(&fold_state));
}

static void stream_8(int arg, void* value) {
  static int input_0;
  switch (arg) {
    case 0:
      input_0 = *((int*)value);
      break;
  }
  static int fold_state = 0;
  int temp16;
  temp16 = fold_state + 1;
  fold_state = temp16;
  stream_9(0, (void*)(&fold_state));
}

static void stream_4(int arg, void* value) {
  static int input_0;
  switch (arg) {
    case 0:
      input_0 = *((int*)value);
      break;
  }
  bool temp17;
  temp17 = (input_0) % 2 == 0;
  stream_5(0, (void*)(&temp17));
}

static void stream_9(int arg, void* value) {
  static int input_0;
  switch (arg) {
    case 0:
      input_0 = *((int*)value);
      break;
  }
  uint8_t temp18;
  temp18 = 104;
  uint8_t temp19;
  temp19 = 101;
  uint8_t temp20;
  temp20 = 108;
  uint8_t temp21;
  temp21 = 108;
  uint8_t temp22;
  temp22 = 111;
  uint8_t temp23;
  temp23 = 13;
  uint8_t temp24;
  temp24 = 10;
  stream_10(0, (void*)(&temp18));
  stream_10(0, (void*)(&temp19));
  stream_10(0, (void*)(&temp20));
  stream_10(0, (void*)(&temp21));
  stream_10(0, (void*)(&temp22));
  stream_10(0, (void*)(&temp23));
  stream_10(0, (void*)(&temp24));
}

static void stream_10(int arg, void* value) {
  static uint8_t input_0;
  switch (arg) {
    case 0:
      input_0 = *((uint8_t*)value);
      break;
  }
  while ((UCSR0A & (1 << UDRE0)) == 0) {
  }
  UDR0 = input_0;
}

static void stream_5(int arg, void* value) {
  static bool input_0;
  switch (arg) {
    case 0:
      input_0 = *((bool*)value);
      break;
  }
  if (input_0) {
    PORTB |= (1 << PB5);
  } else {
    PORTB &= ~(1 << PB5);
  }
}

int main(void) {
  TCCR1B |= (1 << CS12);
  TCCR1B |= (1 << CS10);
  UBRR0H = 0;
  UBRR0L = 103;
  UCSR0C |= (1 << UCSZ01);
  UCSR0C |= (1 << UCSZ00);
  UCSR0B |= (1 << RXEN0);
  UCSR0B |= (1 << TXEN0);
  DDRB |= (1 << PB5);
  while (1) {
    input_timer();
  }
  return 0;
}
